version: "3"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: phpkoans
        stdin_open: true
        tty: true
        command: tail -f /dev/null
        volumes:
            - .:/code
